drop table if exists ${var:DB}.customer;
create external table ${var:DB}.customer (C_CUSTKEY BIGINT,
 C_NAME STRING,
 C_ADDRESS STRING,
 C_NATIONKEY BIGINT,
 C_PHONE STRING,
 C_ACCTBAL DOUBLE,
 C_MKTSEGMENT STRING,
 C_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS ${var:FILE_FORMAT}
LOCATION '${var:LOCATION}/customer';

drop table if exists ${var:KUDU_DB_NAME}.customer;
CREATE TABLE ${var:KUDU_DB_NAME}.customer
PRIMARY KEY (C_CUSTKEY)
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
AS SELECT * FROM ${var:DB}.customer;
