drop table if exists ${var:DB}.partsupp;
create external table ${var:DB}.partsupp (PS_PARTKEY BIGINT,
 PS_SUPPKEY BIGINT,
 PS_AVAILQTY INT,
 PS_SUPPLYCOST DOUBLE,
 PS_COMMENT STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' STORED AS ${var:FILE_FORMAT}
LOCATION'${var:LOCATION}/partsupp';

drop table if exists ${var:KUDU_DB_NAME}.partsupp;
CREATE TABLE ${var:KUDU_DB_NAME}.partsupp
PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
--PARTITION BY HASH(PS_PARTKEY, PS_SUPPKEY) PARTITIONS 16
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU
AS SELECT * FROM ${var:DB}.partsupp;
